name: smart_pagination_pro

description: >
  Production-ready Flutter pagination package with infinite scroll,
  scroll pagination, load more, async/API pagination, Page, Offset,
  and Cursor strategies, search debouncing, filters, sorting,
  refresh,
  race-condition protection, shimmer loading, and responsive UI.

version: 1.0.4

homepage: https://github.com/ravipatel1999/smart_pagination_pro
repository: https://github.com/ravipatel1999/smart_pagination_pro
issue_tracker: https://github.com/ravipatel1999/smart_pagination_pro/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - flutter
  - pagination
  - infinite-scroll
  - scroll-pagination
  - api-pagination